AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 3 API - com.mohshad::spring-boot-aws-lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SpringBootAwsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.mohshad.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        PostClient:
          Type: Api
          Properties:
            Path: /client
            Method: post
        GetAllClients:
          Type: Api
          Properties:
            Path: /client
            Method: get
        GetClient:
          Type: Api
          Properties:
            Path: /client/{id}
            Method: get
